<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PlayBisca_reka-navigation-menu-v-0-t_2c65dd</name>
   <tag></tag>
   <elementGuidId>ca716b78-0bd2-4b93-8efe-518b82edaffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reka-navigation-menu-v-0-trigger-reka-v-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reka-navigation-menu-v-0-trigger-reka-v-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c821d074-da51-43d4-bf91-b7637e5dfb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reka-navigation-menu-v-0-trigger-reka-v-1</value>
      <webElementGuid>2fe7490e-d6ef-48ce-a631-3a32cbf52741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>e313bb2e-e60a-4baf-8930-53c024c58bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f16cc873-c126-4641-8415-f27ab5b741a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>reka-navigation-menu-v-0-content-reka-v-1</value>
      <webElementGuid>831e4d24-d1d3-4919-8ec0-15ad435f22bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>navigation-menu-trigger</value>
      <webElementGuid>d86ffd9a-4912-4311-9c7c-f9ac9a2a8bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground disabled:pointer-events-none disabled:opacity-50 data-[state=open]:hover:bg-accent data-[state=open]:text-accent-foreground data-[state=open]:focus:bg-accent data-[state=open]:bg-accent/50 focus-visible:ring-ring/50 outline-none transition-[color,box-shadow] focus-visible:ring-[3px] focus-visible:outline-1 group</value>
      <webElementGuid>bc98f987-736c-483a-98f9-f761b74cf358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Games</value>
      <webElementGuid>1b5e1521-479f-4356-8ffe-de147e482302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reka-navigation-menu-v-0-trigger-reka-v-1&quot;)</value>
      <webElementGuid>42ce9597-85ab-40fd-b78c-4f88e92fae97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reka-navigation-menu-v-0-trigger-reka-v-1']</value>
      <webElementGuid>dd6ffb45-2d4e-4f31-8b3c-194149064c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav/nav/div/ul/li/button</value>
      <webElementGuid>d06e49d1-7f32-4465-ae3a-b2ba2e4a3ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='♠ PlayBisca'])[1]/following::button[1]</value>
      <webElementGuid>865f119c-d0c5-4c79-8afe-7df51eb91b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::button[1]</value>
      <webElementGuid>ad754749-9f87-455d-8f1f-e23a6a34a437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SinglePlayer Game'])[1]/preceding::button[1]</value>
      <webElementGuid>e8318a48-8f01-4901-bd3c-5cd0cbd09972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Games']/parent::*</value>
      <webElementGuid>296d3f41-8939-4c93-ab9a-712ae4024d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b1e0d8d5-8202-4ad7-8a26-e5abd3c29be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'reka-navigation-menu-v-0-trigger-reka-v-1' and (text() = 'Games' or . = 'Games')]</value>
      <webElementGuid>af2ef861-7818-4858-94f1-60c2af752b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
