<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Jogo casual, sem ranking_option-tile</name>
   <tag></tag>
   <elementGuidId>c3e1a372-25e7-43de-a5ce-b5492efe6b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fd8ef65-c9db-4c57-91ee-0d159a234202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fff4a8aa-73fe-4f3b-a82b-88525ed2f08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-tile</value>
      <webElementGuid>a609b781-e84f-435d-b360-84d5d10e820c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CompetitiveJogo competitivo</value>
      <webElementGuid>721f4a26-5485-47b8-bafa-711d57468b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/main[1]/main[@class=&quot;page-container&quot;]/div[@class=&quot;page-inner page-inner--sm&quot;]/section[@class=&quot;ui-card ui-card--md&quot;]/section[@class=&quot;sp-section&quot;]/div[@class=&quot;sp-options-row&quot;]/button[@class=&quot;option-tile&quot;]</value>
      <webElementGuid>8b7dd408-1a37-4ee3-ac18-7eb9d1649d5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>08399fd9-a16f-4ece-81a3-723e7314c805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/main/div/section/section/div/button[2]</value>
      <webElementGuid>94083e33-3997-4d9a-bf1e-d4d24079cd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>21d20159-6e19-4ba4-89ff-81fbcc85316b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'CompetitiveJogo competitivo' or . = 'CompetitiveJogo competitivo')]</value>
      <webElementGuid>6cfcbbf0-703c-46a9-81a4-baf378d25bb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
