<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mo inicial de 9 cartas_primary-btn</name>
   <tag></tag>
   <elementGuidId>11717deb-e942-47fe-9406-0aa844d72ee7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/main/div/section/footer/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.primary-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ab6c9a8-0a25-4428-bc5f-fca689e7c63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn</value>
      <webElementGuid>3579a776-6361-49a1-843d-64d8e81c959c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Start Game </value>
      <webElementGuid>74270002-a321-420d-b32b-1383e9aeae4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/main[1]/main[@class=&quot;page-container&quot;]/div[@class=&quot;page-inner page-inner--sm&quot;]/section[@class=&quot;ui-card ui-card--md&quot;]/footer[@class=&quot;sp-footer&quot;]/button[@class=&quot;primary-btn&quot;]</value>
      <webElementGuid>c8a81aee-6d62-4abc-a72e-13117e9abe17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/main/div/section/footer/button</value>
      <webElementGuid>cadaace9-b244-4111-b000-e2a58e6f936d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Game']/parent::*</value>
      <webElementGuid>59a31817-92b1-4996-9ac8-4570cda517af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>b3f70bb6-d1b3-4be9-a40f-d5eed9d38c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Start Game ' or . = ' Start Game ')]</value>
      <webElementGuid>4278a418-2769-4fee-a757-ca24559e2df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
