<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Variant_option-tile</name>
   <tag></tag>
   <elementGuidId>71021bd6-ded9-4fbd-89db-ad5c9b7964a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3b6361f-82e7-44ec-97db-96b34d278564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6e30767-a071-448e-8b52-e90520cf3d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-tile</value>
      <webElementGuid>1e761318-3499-4020-ba94-e8f5d0e53506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bisca de 3Mão inicial de 3 cartas</value>
      <webElementGuid>0ee500b5-f79b-433d-bf39-4ade96f0fd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/main[1]/main[@class=&quot;page-container&quot;]/div[@class=&quot;page-inner page-inner--sm&quot;]/section[@class=&quot;ui-card ui-card--md&quot;]/section[@class=&quot;sp-section&quot;]/div[@class=&quot;sp-options-row&quot;]/button[@class=&quot;option-tile&quot;]</value>
      <webElementGuid>51628987-c6da-47c1-ae36-b06b0019c564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>fcfdac7d-3214-41b2-ae1a-5214d7f4c012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/main/div/section/section[3]/div/button</value>
      <webElementGuid>2a945c18-bf79-4cab-b02e-5d71e24e85eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variant'])[1]/following::button[1]</value>
      <webElementGuid>2002246e-e1e2-4955-b342-8e0109a5b9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/button</value>
      <webElementGuid>46a508d7-c719-4c71-a2e3-8128c79381a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Bisca de 3Mão inicial de 3 cartas' or . = 'Bisca de 3Mão inicial de 3 cartas')]</value>
      <webElementGuid>42ce3d3c-5360-4f61-b06d-f5b45bf67812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
