<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Um nico jogo_option-tile</name>
   <tag></tag>
   <elementGuidId>9946b7a9-42fd-4619-9710-3b1f925edb73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ea93df0-9a4e-475f-abfe-b3a0c1e9af12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0531efed-e07d-4816-9977-057ee9f00967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-tile</value>
      <webElementGuid>4f0072b3-cbfb-4e51-9e14-a189a44fc0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MatchMatch até 4 marks</value>
      <webElementGuid>857764cb-54a3-4ce9-be48-c646d2e514a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/main[1]/main[@class=&quot;page-container&quot;]/div[@class=&quot;page-inner page-inner--sm&quot;]/section[@class=&quot;ui-card ui-card--md&quot;]/section[@class=&quot;sp-section&quot;]/div[@class=&quot;sp-options-row&quot;]/button[@class=&quot;option-tile&quot;]</value>
      <webElementGuid>8aa0ac52-26ab-4fbf-b151-be68b7a54753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>c78fe0ed-4e0c-4179-a0df-92374db2f2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/main/div/section/section[2]/div/button[2]</value>
      <webElementGuid>f74fbf24-e4d3-46bf-b5c9-4b6c267efc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/button[2]</value>
      <webElementGuid>c0cfb539-140e-445c-bfc8-37b0eb82372c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'MatchMatch até 4 marks' or . = 'MatchMatch até 4 marks')]</value>
      <webElementGuid>710001f1-9aca-472e-bd38-00aaaef5bdf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
